# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10un6nwBzSTXuK6-ETT5XyhLR2uAE8Ser
"""

!pip install pycryptodome

"""# Sección nueva"""